# Generated by Django 4.2.3 on 2023-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('deporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaNorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('deporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaOeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('deporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaSur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('deporte', models.CharField(max_length=50)),
            ],
        ),
    ]
