# Generated by Django 4.2.3 on 2023-08-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_comentariozo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentarioZo',
        ),
    ]
